name: mirrorchyan_release

on:
  workflow_dispatch:
    inputs:
        tag:
            default: ''
            required: false

jobs:
  mirrorchyan:
    runs-on: macos-latest
    if: ${{ github.repository_owner == 'baoxin1100' }}

    steps:
      - uses: MirrorChyan/uploading-action@v1
        with:
          filetype: latest-release
          filename: "ok-kes-win32-portable-*.exe"
          mirrorchyan_rid: ok-kes
          tag: ${{ inputs.tag }}

          os: win
          arch: x64

          owner: baoxin1100
          repo: ok-kes
          github_token: ${{ secrets.GITHUB_TOKEN }}
          upload_token: ${{ secrets.MirrorChyanUploadToken }}
